---

- name: update package sources and upgrade system
  apt:
      update_cache: yes
      upgrade: yes

- name: Install required packages
  package:
      name: "{{ item }}"
      state: latest
  with_items: "{{ packages }}"

- name: Partition 2nd drive
  filesystem:
      fstype: ext2
      dev: '{{ dockerdisk }}'
      opts: -L DOCKERDRV

- name: Use 2nd drive as docker storageprovider
  mount:
      src: LABEL=DOCKERDRV
      name: /var/lib/docker
      fstype: ext2
      state: mounted

- name: add docker repokey
  apt-key:
        url: "{{ docker_repo_key_src }}"
        state: present

- name: add docker repo to packages sources
  apt_repository:
        repo: "{{ docker_repo_uri }}"
        state: present

- name: install docker
  apt:
      update_cache: yes
      name: docker-ce
      state: latest

- name: Create docker group
  group:
      name: docker
      state: present

- name: Create user for docker
  user:
      name: runner
      group: docker
      state: present

- name: Start dockerd
  service: 
      enabled: yes
      state: restarted

- name: Fetch Container Sources
  git:
      repo: "{{ item.uri }}"
      dest: "{{ item.dest }}"
  with_items: "{{ containers }}"

- name: Build images
  docker_image:
      name: "{{ item.name }}"
      path: "{{ item.file}}"
      state: build
  with_items: "{{ containers }}"
